# Generated by Django 5.1.3 on 2024-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('module1', models.IntegerField()),
                ('module2', models.IntegerField()),
                ('module3', models.IntegerField()),
                ('module4', models.IntegerField()),
                ('module5', models.IntegerField()),
                ('module6', models.IntegerField()),
            ],
        ),
    ]
