# Generated by Django 5.1.3 on 2025-01-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='module1',
            new_name='Big_Data_Architecture_and_Programming',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='module2',
            new_name='Cloud_Computing_And_Techniques',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='module3',
            new_name='Database_Design_and_Implementation',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='module4',
            new_name='Internet_of_Things_Design_Principles',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='module5',
            new_name='Network_Technologies_and_Designe',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='module6',
            new_name='Python_Programming_Methodology_2',
        ),
    ]
