# Generated by Django 5.1.3 on 2025-01-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_module1_studentrecord_big_data_architecture_and_programming_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='Big_Data_Architecture_and_Programming',
            new_name='big_data_architecture_and_programming',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='Cloud_Computing_And_Techniques',
            new_name='cloud_computing_and_techniques',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='Database_Design_and_Implementation',
            new_name='database_design_and_implementation',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='Internet_of_Things_Design_Principles',
            new_name='internet_of_things_design_principles',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='Network_Technologies_and_Designe',
            new_name='network_technologies_and_design',
        ),
        migrations.RenameField(
            model_name='studentrecord',
            old_name='Python_Programming_Methodology_2',
            new_name='python_programming_methodology_2',
        ),
    ]
